window.MemeManagerUI = window.MemeManagerUI || {};
window.MemeManagerUI.state = {
  loading: false,
  error: null,
  managedPackIdFromUrl: String(
    new URLSearchParams(window.location.search).get("managed_pack_id") || "",
  ).trim(),
  selectionState: {
    enabled: false,
    items: new Map(),
  },
  latestEmojiData: {},
  latestTagDescriptions: {},
  dangerConfirmResolver: null,
  dangerConfirmStage: "ack",
  dangerConfirmTimer: null,
  dangerConfirmConfig: null,
  toggleSelectionModeBtn: document.getElementById(
    "toggle-selection-mode-btn",
  ),
  batchMoveBtn: document.getElementById("batch-move-btn"),
  batchDeleteBtn: document.getElementById("batch-delete-btn"),
  clearAllBtn: document.getElementById("clear-all-btn"),
  selectionSummary: document.getElementById("selection-summary"),
  toastContainer: document.getElementById("toast-container"),
  batchContextMenu: document.getElementById("batch-context-menu"),
  batchContextMenuTitle: document.getElementById(
    "batch-context-menu-title",
  ),
  batchContextMenuSubtitle: document.getElementById(
    "batch-context-menu-subtitle",
  ),
  contextMenuDeleteBtn: document.getElementById(
    "context-menu-delete-btn",
  ),
  contextMenuMoveBtn: document.getElementById("context-menu-move-btn"),
  contextMenuCopyBtn: document.getElementById("context-menu-copy-btn"),
  contextMenuPasteBtn: document.getElementById("context-menu-paste-btn"),
  consoleToggleBtn: document.getElementById("console-toggle-btn"),
  directoryToggleBtn: document.getElementById("directory-toggle-btn"),
  sidebarBackdrop: document.getElementById("sidebar-backdrop"),
  leftPanel: document.getElementById("app-sidebar-panel"),
  directoryPanel: document.getElementById("app-directory-panel"),
  dragHud: document.getElementById("drag-hud"),
  dragHudLabel: document.getElementById("drag-hud-label"),
  dragHudCaption: document.getElementById("drag-hud-caption"),
  imagePreviewModalRoot: document.getElementById("image-preview-modal"),
  imagePreviewImg: document.getElementById("image-preview-img"),
  imagePreviewLoading: document.getElementById("image-preview-loading"),
  imagePreviewOriginalBtn: document.getElementById(
    "image-preview-original-btn",
  ),
  imagePreviewCloseBtn: document.getElementById(
    "image-preview-close-btn",
  ),
  moveTargetModalRoot: document.getElementById("move-target-modal"),
  moveTargetModalTitle: document.getElementById(
    "move-target-modal-title",
  ),
  moveTargetModalDescription: document.getElementById(
    "move-target-modal-description",
  ),
  moveTargetList: document.getElementById("move-target-list"),
  moveTargetCancelBtn: document.getElementById("move-target-cancel-btn"),
  categoryEditModalRoot: document.getElementById("category-edit-modal"),
  categoryEditModalTitle: document.getElementById(
    "category-edit-modal-title",
  ),
  categoryEditModalDescription: document.getElementById(
    "category-edit-modal-description",
  ),
  categoryEditNameInput: document.getElementById(
    "category-edit-name-input",
  ),
  categoryEditDescInput: document.getElementById(
    "category-edit-desc-input",
  ),
  categoryEditCancelBtn: document.getElementById(
    "category-edit-cancel-btn",
  ),
  categoryEditSaveBtn: document.getElementById("category-edit-save-btn"),
  confirmModalRoot: document.getElementById("confirm-modal"),
  confirmModalTitle: document.getElementById("confirm-modal-title"),
  confirmModalDescription: document.getElementById(
    "confirm-modal-description",
  ),
  confirmModalCancelBtn: document.getElementById(
    "confirm-modal-cancel-btn",
  ),
  confirmModalConfirmBtn: document.getElementById(
    "confirm-modal-confirm-btn",
  ),
  dangerModalRoot: document.getElementById("danger-confirm-modal"),
  dangerModalTitle: document.getElementById("danger-modal-title"),
  dangerModalDescription: document.getElementById(
    "danger-modal-description",
  ),
  dangerModalStageText: document.getElementById(
    "danger-modal-stage-text",
  ),
  dangerModalAcknowledge: document.getElementById("danger-modal-ack"),
  dangerModalCancelBtn: document.getElementById(
    "danger-modal-cancel-btn",
  ),
  dangerModalConfirmBtn: document.getElementById(
    "danger-modal-confirm-btn",
  ),
  managePackSelect: document.getElementById("manage-pack-select"),
  switchManagePackBtn: document.getElementById("switch-manage-pack-btn"),
  deleteManagePackBtn: document.getElementById("delete-manage-pack-btn"),
  transferCurrentPack: document.getElementById("transfer-current-pack"),
  exportModeInputs: Array.from(
    document.querySelectorAll('input[name="export-mode"]'),
  ),
  exportModeBackup: document.getElementById("export-mode-backup"),
  exportPackDownloadBtn: document.getElementById(
    "export-pack-download-btn",
  ),
  exportPackResult: document.getElementById("export-pack-result"),
  packImportDropzone: document.getElementById("pack-import-dropzone"),
  packImportFile: document.getElementById("pack-import-file"),
  packImportFileLabel: document.getElementById("pack-import-file-label"),
  packImportPreview: document.getElementById("pack-import-preview"),
  packImportPreviewName: document.getElementById(
    "pack-import-preview-name",
  ),
  packImportPreviewFormat: document.getElementById(
    "pack-import-preview-format",
  ),
  packImportImageCount: document.getElementById(
    "pack-import-image-count",
  ),
  packImportCategoryCount: document.getElementById(
    "pack-import-category-count",
  ),
  packImportWarning: document.getElementById("pack-import-warning"),
  packImportSetDefault: document.getElementById(
    "pack-import-set-default",
  ),
  packImportOverwrite: document.getElementById("pack-import-overwrite"),
  packImportResetBtn: document.getElementById("pack-import-reset-btn"),
  packImportConfirmBtn: document.getElementById(
    "pack-import-confirm-btn",
  ),
  packImportResult: document.getElementById("pack-import-result"),
  defaultManagePackId: "",
  activeManagePackId: "",
  managePacksById: new Map(),
  pendingPackImportToken: "",
  exportCapabilityRequestId: 0,
  confirmResolver: null,
  MOBILE_LAYOUT_MEDIA: "(max-width: 960px)",
  DRAG_HUD_OFFSET_X: 18,
  DRAG_HUD_OFFSET_Y: 88,
  LONG_PRESS_DURATION_MS: 2000,
  LONG_PRESS_TICK_MS: 60,
  LONG_PRESS_CANCEL_DISTANCE_PX: 18,
  DRAG_READY_TIMEOUT_MS: 15000,
  longPressState: {
    emojiItem: null,
    pointerId: null,
    startTime: 0,
    startX: 0,
    startY: 0,
    currentX: 0,
    currentY: 0,
    timeoutId: null,
    intervalId: null,
  },
  dragModeState: {
    items: [],
    timeoutId: null,
    pointerId: null,
    activeCategory: null,
    isPointerDragging: false,
    captureElement: null,
    autoScrollFrameId: null,
    lastClientX: 0,
    lastClientY: 0,
  },
  clipboardState: {
    items: [],
  },
  contextMenuState: {
    items: [],
    targetCategory: null,
  },
  uploadStateByCategory: new Map(),
  initialStatusTimerId: null,
  activeCategoryEdit: null,
  pendingMoveTargetItems: [],
  imagePreviewState: null,
  emptyPackGuideShown: false,
  firstUseCatalogGuideShown: false,
};
