window.MemeManagerUI = window.MemeManagerUI || {};

window.MemeManagerUI.state = {
  loading: false,
  error: null,
  managedPackIdFromUrl: String(
    new URLSearchParams(window.location.search).get("managed_pack_id") || "",
  ).trim(),
  latestEmojiData: {},
  latestTagDescriptions: {},
  toastContainer: document.getElementById("toast-container"),
  consoleToggleBtn: document.getElementById("console-toggle-btn"),
  directoryToggleBtn: document.getElementById("directory-toggle-btn"),
  sidebarBackdrop: document.getElementById("sidebar-backdrop"),
  leftPanel: document.getElementById("app-sidebar-panel"),
  directoryPanel: document.getElementById("app-directory-panel"),
  imagePreviewModalRoot: document.getElementById("image-preview-modal"),
  imagePreviewImg: document.getElementById("image-preview-img"),
  imagePreviewLoading: document.getElementById("image-preview-loading"),
  imagePreviewOriginalBtn: document.getElementById("image-preview-original-btn"),
  imagePreviewCloseBtn: document.getElementById("image-preview-close-btn"),
  categoryEditModalRoot: document.getElementById("category-edit-modal"),
  categoryEditModalTitle: document.getElementById("category-edit-modal-title"),
  categoryEditModalDescription: document.getElementById("category-edit-modal-description"),
  categoryEditNameInput: document.getElementById("category-edit-name-input"),
  categoryEditDescInput: document.getElementById("category-edit-desc-input"),
  categoryEditCancelBtn: document.getElementById("category-edit-cancel-btn"),
  categoryEditSaveBtn: document.getElementById("category-edit-save-btn"),
  confirmModalRoot: document.getElementById("confirm-modal"),
  confirmModalTitle: document.getElementById("confirm-modal-title"),
  confirmModalDescription: document.getElementById("confirm-modal-description"),
  confirmModalCancelBtn: document.getElementById("confirm-modal-cancel-btn"),
  confirmModalConfirmBtn: document.getElementById("confirm-modal-confirm-btn"),
  dangerModalRoot: document.getElementById("danger-confirm-modal"),
  dangerModalTitle: document.getElementById("danger-modal-title"),
  dangerModalDescription: document.getElementById("danger-modal-description"),
  dangerModalStageText: document.getElementById("danger-modal-stage-text"),
  dangerModalAcknowledge: document.getElementById("danger-modal-ack"),
  dangerModalCancelBtn: document.getElementById("danger-modal-cancel-btn"),
  dangerModalConfirmBtn: document.getElementById("danger-modal-confirm-btn"),
  managePackSelect: document.getElementById("manage-pack-select"),
  switchManagePackBtn: document.getElementById("switch-manage-pack-btn"),
  deleteManagePackBtn: document.getElementById("delete-manage-pack-btn"),
  defaultManagePackId: "",
  activeManagePackId: "",
  managePacksById: new Map(),
  confirmResolver: null,
  dangerConfirmResolver: null,
  dangerConfirmStage: "ack",
  dangerConfirmTimer: null,
  dangerConfirmConfig: null,
  MOBILE_LAYOUT_MEDIA: "(max-width: 960px)",
  uploadStateByCategory: new Map(),
  initialStatusTimerId: null,
  activeCategoryEdit: null,
  imagePreviewState: null,
};
